### ISSUE TITLE
Feature : Option to limit what controls a user can have when building form

### ISSUE THREAD

**Issue by mkgn** [sethsandaru/vue-form-builder#103]
Is there a possibility to hide certain controls from the designer? For example, I might not want to give the user access to a calendar/file uploder or something else. if there is a feature in global configuration that would be great. don't you think?

Looking at the current documentation it is not possible out of the box

**Comment by sethsandaru** [comment]
@mkgn atm VueFormBuilder only has some basic permissions. Is this one really needed? Looks to me, like specific business requirements from your app.

In my opinion, the designer should be able to use all controls, if you don't want them to use some specific controls (because of any reason), then you can give them a note, which is totally better and VueFormBuilder doesn't need to add more checking logic. 

VueFormBuilder is born to do its best job - Configure and Render the Form. Feel free to fork this project and extend it by your need.

Thanks
