### ISSUE TITLE
Bootstrap read-only attributes in v2.x

### ISSUE THREAD

**Issue by thegoatherder** [sethsandaru/vue-form-builder#34]
Any plans to implement boostrap `readonly` on form inputs:

https://getbootstrap.com/docs/4.0/components/forms/#readonly

In the form builder configuration, this could be represented as a checkbox.

**Comment by sethsandaru** [comment]
Hello @thegoatherder ,

Yes, it's one of the features I would build for the v2.1.0 version. Basically, here is what I think about it:

- Read-only field will stay and will be writeable when some specific fields have inputted.
- Read-only and stay there to show up `aggregate - Math` based on the fields.
- Also - an API to disable/enable the Read-Only field.

So, later version is better instead of doing it and reschedule the release date of v2.0.0.
