### ISSUE TITLE
hook_list_factory.js Uncaught TypeError: _.pluck is not a function 

### ISSUE THREAD

**Issue by grabirg** [sethsandaru/vue-form-builder#4]
I just tried using this component but got this error while trying to add section.

HookList._getFunctions (hook_list_factory.js?5e0f:15)     at HookList.runSequence (hook_list_factory.js?5e0f:89)     at VueComponent.addSection (SectionComponent.vue?217d:82)     at invoker (vendor.js:2525)     at HTMLButtonElement.fn._withTask.fn._withTask (vendor.js:2324) _getFunctions @ hook_list_factory.js?5e0f:15 runSequence @ hook_list_factory.js?5e0f:89 addSection @ SectionComponent.vue?217d:82 invoker @ vendor.js:2525 fn._withTask.fn._withTask @ vendor.js:2324

Please Let me know what am I missing.

**Comment by sethsandaru** [comment]
Hi grabirg, do you use lodash in your project? From my sight right now, I can only guess that you are using lodash instead of underscore (Form Builder will automatically load underscore if **window._** not available) and it's cost an error (your error)

It would be nice if you provide to me some of your code :D
