### ISSUE TITLE
Sidebar is not working properly in responsive mode

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#48]
Sidebar is not opening properly in responsive mode, all the css is same as in demo. Also close button is not working in responsive mode.

![form builder error3](https://user-images.githubusercontent.com/5707050/93426296-5ff98080-f8d9-11ea-8e82-e1e3a94a29ce.png)

**Comment by sethsandaru** [comment]
Hi @abhimanusharma ,

I would suggest this: don't configure your form in Mobile view. It doesn't make any senses to do it because the screen is too small,... It would cost a lot of your time also. When you're working on the desktop view, it would be faster.

But the `FormRenderer` is working fine for responsive mode.

Thanks. I'll close this ticket, feel free to open again.
