### ISSUE TITLE
Unable to add controls to online demo

### ISSUE THREAD

**Issue by abhilashdonepudi** [sethsandaru/vue-form-builder#52]
I am might be doing something wrong. Is there a specific way to add controls to the form ? Is there a video somewhere of the demo ?

I am using following demo.

https://vue-form-builder.herokuapp.com

**Comment by abhimanusharma** [comment]
@abhilashdonepudi Follow below steps:

1. Click on **⊕ Add Section**
2. Click on **Normal Block**
3. Then click on **⊕ Add Control**
4. Now from _Choose your control_ sidebar Click on any control 
for example **Input field**. Fill you configuration and click "Save and close".

Following these steps you can easily add any control you want in the demo.

**Comment by abhilashdonepudi** [comment]
I was trying to drag the control instead of simple clicking it. So, dragging doesn’t work ?

**Comment by abhimanusharma** [comment]
@abhilashdonepudi Please refer [Drag and Drop](https://github.com/sethsandaru/vue-form-builder/issues/50)
to see the available options for drag and drop.

**Comment by sethsandaru** [comment]
Hello @abhilashdonepudi ,

For the @2.0.0, the Vue Form Builder's controls can't be drag into the container. You have to click it in order to add a new control into a Section.

P/s: Thanks @abhimanusharma for the answers!

I'll close this issue, feel free to re-open if you have more issues related to this!
