### ISSUE TITLE
File upload control is not present in controls list.

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#55]
I see file upload control was in the todo list of 2.0.0 but it is not present in the current version.
I can't find new todo list for current version and upcoming version as there is no new dev branch present.
Tag for version 1.x.x is also not present (need for learning purpose).
I can add that using some 3rd party package and custom control plugin option but that might cause some compatibility issue.
(I am already struggling with that by using bunch of packages).

PS: I could not able to get in touch with you via email. Hope you will get time to reply my email.

**Comment by sethsandaru** [comment]
Hello @abhimanusharma ,

That was my original plan, but I have to postpone it because it's quite complicated and I haven't come up with a better approach to create File Upload control. Likes:

- Ajax Upload or normal file submit
- Preview (normal file, image,...)
- Validation
- Upload progress
- ...

I think I would develop a simple File Upload Control first for the @2.1.0 . Then improve it later version by version.

Thanks.

P/s: I did respond to your email 3 days ago. Please kindly check. your email again.

**Comment by abhimanusharma** [comment]
@sethsandaru I think this [File uploader documentation](https://lian-yue.github.io/vue-upload-component/#/documents) provides complete customization of file upload. In example tab we can see the options button which can provide the type of customization we need in this form builder from frontend. You can check this out [vue-upload-component](https://github.com/lian-yue/vue-upload-component).

[Watch Video](https://www.loom.com/share/5f08935d0a4f41b188d95aebd702e538)

**Comment by sethsandaru** [comment]
@abhimanusharma Thanks for the suggestion. I checked this: https://bundlephobia.com/result?p=vue-upload-component@2.8.20 and quite ok for me. Seems like it's not a very big deal to put it in Vue Form Builder.

**Comment by abhimanusharma** [comment]
@sethsandaru are you going to release this in the current version?

**Comment by sethsandaru** [comment]
@abhimanusharma No, @2.1.0 will be the version I included that control. I'm still gathering enhancement ideas for the @2.1.0
Looks promising so far :D

**Comment by mehmetcansahin** [comment]
We are excited for upload control.
