### ISSUE TITLE
Why i cant get the css styles?

### ISSUE THREAD

**Issue by osmelg** [sethsandaru/vue-form-builder#63]
in main.js
import {VueFormBuilderPlugin} from 'v-form-builder'
import 'v-form-builder/dist/v-form-builder.css' //load CSS from your App
Vue.use(VueFormBuilderPlugin, options)

Then in the Component
FormBuilder v-model="configuration"></FormBuilder

The styles of the FormBuilder doenst show well
![Untitled](https://user-images.githubusercontent.com/15698737/95878686-7e6d6300-0d43-11eb-99a5-e9c370f5395b.jpg)

Im missing something?

**Comment by sethsandaru** [comment]
Hello @osmelg ,

I think I didn't mention it in the Documentation but you have to **import** your own **Boostrap 4/Material CSS** before the `v-form-builder.css` in order to see the styling.

I didn't and don't want to import the whole Bootstrap/Material into the Vue Form Builder because:   
- It doesn't make sense since everybody's projects should have their own CSS already, why import more.
- It makes the final bundle bigger.

Thanks. Feel free to open this again if you have more questions related to this issue.

**Comment by karosaxy** [comment]
please can you give a guide as to how this can be done?

**Comment by sethsandaru** [comment]
Hi all,

It works from my side and my demo projects. Please make sure that you guys have `css-loader` installed from your webpack 

https://webpack.js.org/loaders/css-loader/
