### ISSUE TITLE
formbuilder localization

### ISSUE THREAD

**Issue by Dontorpedo** [sethsandaru/vue-form-builder#81]
hi, 

do you plan or is it possible to localize the form builder? i didn't find any language files :(

thx

**Comment by sethsandaru** [comment]
Hey @Dontorpedo ,

Yes but not for now. The plan of Localization/Translatable Form is in v2.2.0

For now, you can do another approach like this: Create a Form for a specific Language, eg:

- Form A (EN)
- Form B (DE)
- Form ...

It's too bad because we need to maintain a lot of form. But in the future, when the feature arrived, you only need to translate your fields, sections again in 1 form.

Thanks
